# Generated by Django 4.1.7 on 2023-07-11 07:21

from django.db import migrations, models
import workwhere.models


class Migration(migrations.Migration):

    dependencies = [
        ('workwhere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infotext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HowTo', max_length=80)),
                ('content', models.TextField(default='This is some help text', help_text='Use html for formatting.')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_region', models.CharField(default='ES-AN', help_text='Set ISO region for correct holidays.', max_length=20, validators=[workwhere.models.validate_iso_region])),
                ('min_office_percent', models.PositiveIntegerField(default=20, help_text='Threshold for background color in summary table.', validators=[workwhere.models.validate_min_office_percent])),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
    ]
