# Generated by Django 4.1.7 on 2023-04-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workwhere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('floormap', models.ImageField(upload_to='floormaps')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workwhere.location')),
            ],
        ),
    ]
