# Generated by Django 4.1.7 on 2023-04-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workwhere', '0003_rename_floorplan_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
