# Generated by Django 4.1.7 on 2023-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workwhere', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
