# Generated by Django 4.1.7 on 2023-04-21 18:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workwhere', '0005_employee_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floormap',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/floormaps'), upload_to=''),
        ),
    ]
