# Generated by Django 4.1.7 on 2023-04-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workwhere', '0006_alter_floor_floormap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floormap',
            field=models.ImageField(upload_to='floormaps'),
        ),
    ]
