# Generated by Django 4.1.7 on 2023-04-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workwhere', '0007_alter_floor_floormap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dlr_id',
            new_name='user_id',
        ),
    ]
